//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Source) DeepCopyInto(out *Source) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Source.
func (in *Source) DeepCopy() *Source {
	if in == nil {
		return nil
	}
	out := new(Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Source) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceInitParameters) DeepCopyInto(out *SourceInitParameters) {
	*out = *in
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlowRef != nil {
		in, out := &in.EnrollmentFlowRef, &out.EnrollmentFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.EnrollmentFlowSelector != nil {
		in, out := &in.EnrollmentFlowSelector, &out.EnrollmentFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.Krb5Conf != nil {
		in, out := &in.Krb5Conf, &out.Krb5Conf
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PasswordLoginUpdateInternalPassword != nil {
		in, out := &in.PasswordLoginUpdateInternalPassword, &out.PasswordLoginUpdateInternalPassword
		*out = new(bool)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.SpnegoCcache != nil {
		in, out := &in.SpnegoCcache, &out.SpnegoCcache
		*out = new(string)
		**out = **in
	}
	if in.SpnegoKeytabSecretRef != nil {
		in, out := &in.SpnegoKeytabSecretRef, &out.SpnegoKeytabSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.SpnegoServerName != nil {
		in, out := &in.SpnegoServerName, &out.SpnegoServerName
		*out = new(string)
		**out = **in
	}
	if in.SyncCcache != nil {
		in, out := &in.SyncCcache, &out.SyncCcache
		*out = new(string)
		**out = **in
	}
	if in.SyncKeytabSecretRef != nil {
		in, out := &in.SyncKeytabSecretRef, &out.SyncKeytabSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.SyncPasswordSecretRef != nil {
		in, out := &in.SyncPasswordSecretRef, &out.SyncPasswordSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.SyncPrincipal != nil {
		in, out := &in.SyncPrincipal, &out.SyncPrincipal
		*out = new(string)
		**out = **in
	}
	if in.SyncUsers != nil {
		in, out := &in.SyncUsers, &out.SyncUsers
		*out = new(bool)
		**out = **in
	}
	if in.SyncUsersPassword != nil {
		in, out := &in.SyncUsersPassword, &out.SyncUsersPassword
		*out = new(bool)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceInitParameters.
func (in *SourceInitParameters) DeepCopy() *SourceInitParameters {
	if in == nil {
		return nil
	}
	out := new(SourceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceList) DeepCopyInto(out *SourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Source, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceList.
func (in *SourceList) DeepCopy() *SourceList {
	if in == nil {
		return nil
	}
	out := new(SourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceObservation) DeepCopyInto(out *SourceObservation) {
	*out = *in
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Krb5Conf != nil {
		in, out := &in.Krb5Conf, &out.Krb5Conf
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PasswordLoginUpdateInternalPassword != nil {
		in, out := &in.PasswordLoginUpdateInternalPassword, &out.PasswordLoginUpdateInternalPassword
		*out = new(bool)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.SpnegoCcache != nil {
		in, out := &in.SpnegoCcache, &out.SpnegoCcache
		*out = new(string)
		**out = **in
	}
	if in.SpnegoServerName != nil {
		in, out := &in.SpnegoServerName, &out.SpnegoServerName
		*out = new(string)
		**out = **in
	}
	if in.SyncCcache != nil {
		in, out := &in.SyncCcache, &out.SyncCcache
		*out = new(string)
		**out = **in
	}
	if in.SyncPrincipal != nil {
		in, out := &in.SyncPrincipal, &out.SyncPrincipal
		*out = new(string)
		**out = **in
	}
	if in.SyncUsers != nil {
		in, out := &in.SyncUsers, &out.SyncUsers
		*out = new(bool)
		**out = **in
	}
	if in.SyncUsersPassword != nil {
		in, out := &in.SyncUsersPassword, &out.SyncUsersPassword
		*out = new(bool)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceObservation.
func (in *SourceObservation) DeepCopy() *SourceObservation {
	if in == nil {
		return nil
	}
	out := new(SourceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceParameters) DeepCopyInto(out *SourceParameters) {
	*out = *in
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlowRef != nil {
		in, out := &in.EnrollmentFlowRef, &out.EnrollmentFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.EnrollmentFlowSelector != nil {
		in, out := &in.EnrollmentFlowSelector, &out.EnrollmentFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.Krb5Conf != nil {
		in, out := &in.Krb5Conf, &out.Krb5Conf
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PasswordLoginUpdateInternalPassword != nil {
		in, out := &in.PasswordLoginUpdateInternalPassword, &out.PasswordLoginUpdateInternalPassword
		*out = new(bool)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.SpnegoCcache != nil {
		in, out := &in.SpnegoCcache, &out.SpnegoCcache
		*out = new(string)
		**out = **in
	}
	if in.SpnegoKeytabSecretRef != nil {
		in, out := &in.SpnegoKeytabSecretRef, &out.SpnegoKeytabSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.SpnegoServerName != nil {
		in, out := &in.SpnegoServerName, &out.SpnegoServerName
		*out = new(string)
		**out = **in
	}
	if in.SyncCcache != nil {
		in, out := &in.SyncCcache, &out.SyncCcache
		*out = new(string)
		**out = **in
	}
	if in.SyncKeytabSecretRef != nil {
		in, out := &in.SyncKeytabSecretRef, &out.SyncKeytabSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.SyncPasswordSecretRef != nil {
		in, out := &in.SyncPasswordSecretRef, &out.SyncPasswordSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.SyncPrincipal != nil {
		in, out := &in.SyncPrincipal, &out.SyncPrincipal
		*out = new(string)
		**out = **in
	}
	if in.SyncUsers != nil {
		in, out := &in.SyncUsers, &out.SyncUsers
		*out = new(bool)
		**out = **in
	}
	if in.SyncUsersPassword != nil {
		in, out := &in.SyncUsersPassword, &out.SyncUsersPassword
		*out = new(bool)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceParameters.
func (in *SourceParameters) DeepCopy() *SourceParameters {
	if in == nil {
		return nil
	}
	out := new(SourceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSpec) DeepCopyInto(out *SourceSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSpec.
func (in *SourceSpec) DeepCopy() *SourceSpec {
	if in == nil {
		return nil
	}
	out := new(SourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceStatus) DeepCopyInto(out *SourceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceStatus.
func (in *SourceStatus) DeepCopy() *SourceStatus {
	if in == nil {
		return nil
	}
	out := new(SourceStatus)
	in.DeepCopyInto(out)
	return out
}
