// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ProviderInitParameters struct {

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	Credentials *string `json:"credentials,omitempty" tf:"credentials,omitempty"`

	DefaultGroupEmailDomain *string `json:"defaultGroupEmailDomain,omitempty" tf:"default_group_email_domain,omitempty"`

	DelegatedSubject *string `json:"delegatedSubject,omitempty" tf:"delegated_subject,omitempty"`

	// Defaults to `false`.
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	ExcludeUsersServiceAccount *bool `json:"excludeUsersServiceAccount,omitempty" tf:"exclude_users_service_account,omitempty"`

	FilterGroup *string `json:"filterGroup,omitempty" tf:"filter_group,omitempty"`

	// Allowed values:
	// - `delete`
	// - `do_nothing`
	// Defaults to `delete`.
	GroupDeleteAction *string `json:"groupDeleteAction,omitempty" tf:"group_delete_action,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/googleworkspace/v1alpha1.ProviderPropertyMapping
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/googleworkspace/v1alpha1.ProviderPropertyMapping
	PropertyMappingsGroup []*string `json:"propertyMappingsGroup,omitempty" tf:"property_mappings_group,omitempty"`

	// References to ProviderPropertyMapping in googleworkspace to populate propertyMappingsGroup.
	// +kubebuilder:validation:Optional
	PropertyMappingsGroupRefs []v1.NamespacedReference `json:"propertyMappingsGroupRefs,omitempty" tf:"-"`

	// Selector for a list of ProviderPropertyMapping in googleworkspace to populate propertyMappingsGroup.
	// +kubebuilder:validation:Optional
	PropertyMappingsGroupSelector *v1.NamespacedSelector `json:"propertyMappingsGroupSelector,omitempty" tf:"-"`

	// References to ProviderPropertyMapping in googleworkspace to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsRefs []v1.NamespacedReference `json:"propertyMappingsRefs,omitempty" tf:"-"`

	// Selector for a list of ProviderPropertyMapping in googleworkspace to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsSelector *v1.NamespacedSelector `json:"propertyMappingsSelector,omitempty" tf:"-"`

	// Allowed values:
	// - `do_nothing`
	// - `delete`
	// - `suspend`
	// Defaults to `delete`.
	UserDeleteAction *string `json:"userDeleteAction,omitempty" tf:"user_delete_action,omitempty"`
}

type ProviderObservation struct {

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	Credentials *string `json:"credentials,omitempty" tf:"credentials,omitempty"`

	DefaultGroupEmailDomain *string `json:"defaultGroupEmailDomain,omitempty" tf:"default_group_email_domain,omitempty"`

	DelegatedSubject *string `json:"delegatedSubject,omitempty" tf:"delegated_subject,omitempty"`

	// Defaults to `false`.
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	ExcludeUsersServiceAccount *bool `json:"excludeUsersServiceAccount,omitempty" tf:"exclude_users_service_account,omitempty"`

	FilterGroup *string `json:"filterGroup,omitempty" tf:"filter_group,omitempty"`

	// Allowed values:
	// - `delete`
	// - `do_nothing`
	// Defaults to `delete`.
	GroupDeleteAction *string `json:"groupDeleteAction,omitempty" tf:"group_delete_action,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	PropertyMappingsGroup []*string `json:"propertyMappingsGroup,omitempty" tf:"property_mappings_group,omitempty"`

	// Allowed values:
	// - `do_nothing`
	// - `delete`
	// - `suspend`
	// Defaults to `delete`.
	UserDeleteAction *string `json:"userDeleteAction,omitempty" tf:"user_delete_action,omitempty"`
}

type ProviderParameters struct {

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	// +kubebuilder:validation:Optional
	Credentials *string `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// +kubebuilder:validation:Optional
	DefaultGroupEmailDomain *string `json:"defaultGroupEmailDomain,omitempty" tf:"default_group_email_domain,omitempty"`

	// +kubebuilder:validation:Optional
	DelegatedSubject *string `json:"delegatedSubject,omitempty" tf:"delegated_subject,omitempty"`

	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeUsersServiceAccount *bool `json:"excludeUsersServiceAccount,omitempty" tf:"exclude_users_service_account,omitempty"`

	// +kubebuilder:validation:Optional
	FilterGroup *string `json:"filterGroup,omitempty" tf:"filter_group,omitempty"`

	// Allowed values:
	// - `delete`
	// - `do_nothing`
	// Defaults to `delete`.
	// +kubebuilder:validation:Optional
	GroupDeleteAction *string `json:"groupDeleteAction,omitempty" tf:"group_delete_action,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/googleworkspace/v1alpha1.ProviderPropertyMapping
	// +kubebuilder:validation:Optional
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/googleworkspace/v1alpha1.ProviderPropertyMapping
	// +kubebuilder:validation:Optional
	PropertyMappingsGroup []*string `json:"propertyMappingsGroup,omitempty" tf:"property_mappings_group,omitempty"`

	// References to ProviderPropertyMapping in googleworkspace to populate propertyMappingsGroup.
	// +kubebuilder:validation:Optional
	PropertyMappingsGroupRefs []v1.NamespacedReference `json:"propertyMappingsGroupRefs,omitempty" tf:"-"`

	// Selector for a list of ProviderPropertyMapping in googleworkspace to populate propertyMappingsGroup.
	// +kubebuilder:validation:Optional
	PropertyMappingsGroupSelector *v1.NamespacedSelector `json:"propertyMappingsGroupSelector,omitempty" tf:"-"`

	// References to ProviderPropertyMapping in googleworkspace to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsRefs []v1.NamespacedReference `json:"propertyMappingsRefs,omitempty" tf:"-"`

	// Selector for a list of ProviderPropertyMapping in googleworkspace to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsSelector *v1.NamespacedSelector `json:"propertyMappingsSelector,omitempty" tf:"-"`

	// Allowed values:
	// - `do_nothing`
	// - `delete`
	// - `suspend`
	// Defaults to `delete`.
	// +kubebuilder:validation:Optional
	UserDeleteAction *string `json:"userDeleteAction,omitempty" tf:"user_delete_action,omitempty"`
}

// ProviderSpec defines the desired state of Provider
type ProviderSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProviderParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProviderInitParameters `json:"initProvider,omitempty"`
}

// ProviderStatus defines the observed state of Provider.
type ProviderStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProviderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Provider is the Schema for the Providers API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,authentik}
type Provider struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.defaultGroupEmailDomain) || (has(self.initProvider) && has(self.initProvider.defaultGroupEmailDomain))",message="spec.forProvider.defaultGroupEmailDomain is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ProviderSpec   `json:"spec"`
	Status ProviderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProviderList contains a list of Providers
type ProviderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Provider `json:"items"`
}

// Repository type metadata.
var (
	Provider_Kind             = "Provider"
	Provider_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Provider_Kind}.String()
	Provider_KindAPIVersion   = Provider_Kind + "." + CRDGroupVersion.String()
	Provider_GroupVersionKind = CRDGroupVersion.WithKind(Provider_Kind)
)

func init() {
	SchemeBuilder.Register(&Provider{}, &ProviderList{})
}
