//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Scim) DeepCopyInto(out *Scim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Scim.
func (in *Scim) DeepCopy() *Scim {
	if in == nil {
		return nil
	}
	out := new(Scim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Scim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScimInitParameters) DeepCopyInto(out *ScimInitParameters) {
	*out = *in
	if in.CompatibilityMode != nil {
		in, out := &in.CompatibilityMode, &out.CompatibilityMode
		*out = new(string)
		**out = **in
	}
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
	if in.ExcludeUsersServiceAccount != nil {
		in, out := &in.ExcludeUsersServiceAccount, &out.ExcludeUsersServiceAccount
		*out = new(bool)
		**out = **in
	}
	if in.FilterGroup != nil {
		in, out := &in.FilterGroup, &out.FilterGroup
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	in.TokenSecretRef.DeepCopyInto(&out.TokenSecretRef)
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScimInitParameters.
func (in *ScimInitParameters) DeepCopy() *ScimInitParameters {
	if in == nil {
		return nil
	}
	out := new(ScimInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScimList) DeepCopyInto(out *ScimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Scim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScimList.
func (in *ScimList) DeepCopy() *ScimList {
	if in == nil {
		return nil
	}
	out := new(ScimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScimObservation) DeepCopyInto(out *ScimObservation) {
	*out = *in
	if in.CompatibilityMode != nil {
		in, out := &in.CompatibilityMode, &out.CompatibilityMode
		*out = new(string)
		**out = **in
	}
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
	if in.ExcludeUsersServiceAccount != nil {
		in, out := &in.ExcludeUsersServiceAccount, &out.ExcludeUsersServiceAccount
		*out = new(bool)
		**out = **in
	}
	if in.FilterGroup != nil {
		in, out := &in.FilterGroup, &out.FilterGroup
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScimObservation.
func (in *ScimObservation) DeepCopy() *ScimObservation {
	if in == nil {
		return nil
	}
	out := new(ScimObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScimParameters) DeepCopyInto(out *ScimParameters) {
	*out = *in
	if in.CompatibilityMode != nil {
		in, out := &in.CompatibilityMode, &out.CompatibilityMode
		*out = new(string)
		**out = **in
	}
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
	if in.ExcludeUsersServiceAccount != nil {
		in, out := &in.ExcludeUsersServiceAccount, &out.ExcludeUsersServiceAccount
		*out = new(bool)
		**out = **in
	}
	if in.FilterGroup != nil {
		in, out := &in.FilterGroup, &out.FilterGroup
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	in.TokenSecretRef.DeepCopyInto(&out.TokenSecretRef)
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScimParameters.
func (in *ScimParameters) DeepCopy() *ScimParameters {
	if in == nil {
		return nil
	}
	out := new(ScimParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScimSpec) DeepCopyInto(out *ScimSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScimSpec.
func (in *ScimSpec) DeepCopy() *ScimSpec {
	if in == nil {
		return nil
	}
	out := new(ScimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScimStatus) DeepCopyInto(out *ScimStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScimStatus.
func (in *ScimStatus) DeepCopy() *ScimStatus {
	if in == nil {
		return nil
	}
	out := new(ScimStatus)
	in.DeepCopyInto(out)
	return out
}
