// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ProviderInitParameters struct {

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/flows/v1alpha1.Flow
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	// Reference to a Flow in flows to populate authenticationFlow.
	// +kubebuilder:validation:Optional
	AuthenticationFlowRef *v1.NamespacedReference `json:"authenticationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate authenticationFlow.
	// +kubebuilder:validation:Optional
	AuthenticationFlowSelector *v1.NamespacedSelector `json:"authenticationFlowSelector,omitempty" tf:"-"`

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/flows/v1alpha1.Flow
	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// Reference to a Flow in flows to populate authorizationFlow.
	// +kubebuilder:validation:Optional
	AuthorizationFlowRef *v1.NamespacedReference `json:"authorizationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate authorizationFlow.
	// +kubebuilder:validation:Optional
	AuthorizationFlowSelector *v1.NamespacedSelector `json:"authorizationFlowSelector,omitempty" tf:"-"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=0`.
	ConnectionExpiry *string `json:"connectionExpiry,omitempty" tf:"connection_expiry,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/rac/v1alpha1.ProviderPropertyMapping
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// References to ProviderPropertyMapping in rac to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsRefs []v1.NamespacedReference `json:"propertyMappingsRefs,omitempty" tf:"-"`

	// Selector for a list of ProviderPropertyMapping in rac to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsSelector *v1.NamespacedSelector `json:"propertyMappingsSelector,omitempty" tf:"-"`

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	Settings *string `json:"settings,omitempty" tf:"settings,omitempty"`
}

type ProviderObservation struct {
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=0`.
	ConnectionExpiry *string `json:"connectionExpiry,omitempty" tf:"connection_expiry,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	Settings *string `json:"settings,omitempty" tf:"settings,omitempty"`
}

type ProviderParameters struct {

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/flows/v1alpha1.Flow
	// +kubebuilder:validation:Optional
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	// Reference to a Flow in flows to populate authenticationFlow.
	// +kubebuilder:validation:Optional
	AuthenticationFlowRef *v1.NamespacedReference `json:"authenticationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate authenticationFlow.
	// +kubebuilder:validation:Optional
	AuthenticationFlowSelector *v1.NamespacedSelector `json:"authenticationFlowSelector,omitempty" tf:"-"`

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/flows/v1alpha1.Flow
	// +kubebuilder:validation:Optional
	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// Reference to a Flow in flows to populate authorizationFlow.
	// +kubebuilder:validation:Optional
	AuthorizationFlowRef *v1.NamespacedReference `json:"authorizationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate authorizationFlow.
	// +kubebuilder:validation:Optional
	AuthorizationFlowSelector *v1.NamespacedSelector `json:"authorizationFlowSelector,omitempty" tf:"-"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=0`.
	// +kubebuilder:validation:Optional
	ConnectionExpiry *string `json:"connectionExpiry,omitempty" tf:"connection_expiry,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/rac/v1alpha1.ProviderPropertyMapping
	// +kubebuilder:validation:Optional
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// References to ProviderPropertyMapping in rac to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsRefs []v1.NamespacedReference `json:"propertyMappingsRefs,omitempty" tf:"-"`

	// Selector for a list of ProviderPropertyMapping in rac to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsSelector *v1.NamespacedSelector `json:"propertyMappingsSelector,omitempty" tf:"-"`

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	// +kubebuilder:validation:Optional
	Settings *string `json:"settings,omitempty" tf:"settings,omitempty"`
}

// ProviderSpec defines the desired state of Provider
type ProviderSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProviderParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProviderInitParameters `json:"initProvider,omitempty"`
}

// ProviderStatus defines the observed state of Provider.
type ProviderStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProviderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Provider is the Schema for the Providers API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,authentik}
type Provider struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ProviderSpec   `json:"spec"`
	Status ProviderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProviderList contains a list of Providers
type ProviderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Provider `json:"items"`
}

// Repository type metadata.
var (
	Provider_Kind             = "Provider"
	Provider_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Provider_Kind}.String()
	Provider_KindAPIVersion   = Provider_Kind + "." + CRDGroupVersion.String()
	Provider_GroupVersionKind = CRDGroupVersion.WithKind(Provider_Kind)
)

func init() {
	SchemeBuilder.Register(&Provider{}, &ProviderList{})
}
