// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/unbounded-tech/provider-authentik/apis/namespaced/oauth2/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Provider.
func (mg *Provider) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromFloatPtrValues(mg.Spec.ForProvider.JwtFederationProviders),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.JwtFederationProvidersRefs,
		Selector:      mg.Spec.ForProvider.JwtFederationProvidersSelector,
		To: reference.To{
			List:    &v1alpha1.ProviderList{},
			Managed: &v1alpha1.Provider{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.JwtFederationProviders")
	}
	mg.Spec.ForProvider.JwtFederationProviders = reference.ToFloatPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.JwtFederationProvidersRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromFloatPtrValues(mg.Spec.InitProvider.JwtFederationProviders),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.JwtFederationProvidersRefs,
		Selector:      mg.Spec.InitProvider.JwtFederationProvidersSelector,
		To: reference.To{
			List:    &v1alpha1.ProviderList{},
			Managed: &v1alpha1.Provider{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.JwtFederationProviders")
	}
	mg.Spec.InitProvider.JwtFederationProviders = reference.ToFloatPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.JwtFederationProvidersRefs = mrsp.ResolvedReferences

	return nil
}
