// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ProviderInitParameters struct {

	// Format: hours=1;minutes=2;seconds=3. Defaults to `days=30`.
	EventRetention *string `json:"eventRetention,omitempty" tf:"event_retention,omitempty"`

	// JWTs issued by any of the configured providers can be used to authenticate on behalf of this provider.
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/oauth2/v1alpha1.Provider
	JwtFederationProviders []*float64 `json:"jwtFederationProviders,omitempty" tf:"jwt_federation_providers,omitempty"`

	// References to Provider in oauth2 to populate jwtFederationProviders.
	// +kubebuilder:validation:Optional
	JwtFederationProvidersRefs []v1.NamespacedReference `json:"jwtFederationProvidersRefs,omitempty" tf:"-"`

	// Selector for a list of Provider in oauth2 to populate jwtFederationProviders.
	// +kubebuilder:validation:Optional
	JwtFederationProvidersSelector *v1.NamespacedSelector `json:"jwtFederationProvidersSelector,omitempty" tf:"-"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	SigningKey *string `json:"signingKey,omitempty" tf:"signing_key,omitempty"`
}

type ProviderObservation struct {

	// Format: hours=1;minutes=2;seconds=3. Defaults to `days=30`.
	EventRetention *string `json:"eventRetention,omitempty" tf:"event_retention,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// JWTs issued by any of the configured providers can be used to authenticate on behalf of this provider.
	JwtFederationProviders []*float64 `json:"jwtFederationProviders,omitempty" tf:"jwt_federation_providers,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	SigningKey *string `json:"signingKey,omitempty" tf:"signing_key,omitempty"`
}

type ProviderParameters struct {

	// Format: hours=1;minutes=2;seconds=3. Defaults to `days=30`.
	// +kubebuilder:validation:Optional
	EventRetention *string `json:"eventRetention,omitempty" tf:"event_retention,omitempty"`

	// JWTs issued by any of the configured providers can be used to authenticate on behalf of this provider.
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/oauth2/v1alpha1.Provider
	// +kubebuilder:validation:Optional
	JwtFederationProviders []*float64 `json:"jwtFederationProviders,omitempty" tf:"jwt_federation_providers,omitempty"`

	// References to Provider in oauth2 to populate jwtFederationProviders.
	// +kubebuilder:validation:Optional
	JwtFederationProvidersRefs []v1.NamespacedReference `json:"jwtFederationProvidersRefs,omitempty" tf:"-"`

	// Selector for a list of Provider in oauth2 to populate jwtFederationProviders.
	// +kubebuilder:validation:Optional
	JwtFederationProvidersSelector *v1.NamespacedSelector `json:"jwtFederationProvidersSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	SigningKey *string `json:"signingKey,omitempty" tf:"signing_key,omitempty"`
}

// ProviderSpec defines the desired state of Provider
type ProviderSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProviderParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProviderInitParameters `json:"initProvider,omitempty"`
}

// ProviderStatus defines the observed state of Provider.
type ProviderStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProviderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Provider is the Schema for the Providers API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,authentik}
type Provider struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ProviderSpec   `json:"spec"`
	Status ProviderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProviderList contains a list of Providers
type ProviderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Provider `json:"items"`
}

// Repository type metadata.
var (
	Provider_Kind             = "Provider"
	Provider_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Provider_Kind}.String()
	Provider_KindAPIVersion   = Provider_Kind + "." + CRDGroupVersion.String()
	Provider_GroupVersionKind = CRDGroupVersion.WithKind(Provider_Kind)
)

func init() {
	SchemeBuilder.Register(&Provider{}, &ProviderList{})
}
