// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha11 "github.com/unbounded-tech/provider-authentik/apis/namespaced/k8s/v1alpha1"
	v1alpha1 "github.com/unbounded-tech/provider-authentik/apis/namespaced/proxy/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Outpost.
func (mg *Outpost) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromFloatPtrValues(mg.Spec.ForProvider.ProtocolProviders),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.ProtocolProvidersRefs,
		Selector:      mg.Spec.ForProvider.ProtocolProvidersSelector,
		To: reference.To{
			List:    &v1alpha1.ProviderList{},
			Managed: &v1alpha1.Provider{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProtocolProviders")
	}
	mg.Spec.ForProvider.ProtocolProviders = reference.ToFloatPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.ProtocolProvidersRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServiceConnection),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ServiceConnectionRef,
		Selector:     mg.Spec.ForProvider.ServiceConnectionSelector,
		To: reference.To{
			List:    &v1alpha11.ServiceConnectionList{},
			Managed: &v1alpha11.ServiceConnection{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServiceConnection")
	}
	mg.Spec.ForProvider.ServiceConnection = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServiceConnectionRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromFloatPtrValues(mg.Spec.InitProvider.ProtocolProviders),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.ProtocolProvidersRefs,
		Selector:      mg.Spec.InitProvider.ProtocolProvidersSelector,
		To: reference.To{
			List:    &v1alpha1.ProviderList{},
			Managed: &v1alpha1.Provider{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProtocolProviders")
	}
	mg.Spec.InitProvider.ProtocolProviders = reference.ToFloatPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.ProtocolProvidersRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ServiceConnection),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ServiceConnectionRef,
		Selector:     mg.Spec.InitProvider.ServiceConnectionSelector,
		To: reference.To{
			List:    &v1alpha11.ServiceConnectionList{},
			Managed: &v1alpha11.ServiceConnection{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ServiceConnection")
	}
	mg.Spec.InitProvider.ServiceConnection = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ServiceConnectionRef = rsp.ResolvedReference

	return nil
}
