apiVersion: ldap.authentik.m.crossplane.io/v1alpha1
kind: Provider
metadata:
  annotations:
    meta.upbound.io/example-id: ldap/v1alpha1/provider
  labels:
    testing.upbound.io/example-name: name
  name: name
  namespace: crossplane-system
spec:
  forProvider:
    baseDn: dc=ldap,dc=goauthentik,dc=io
    bindFlowSelector:
      matchLabels:
        testing.upbound.io/example-name: authentik_flow
    name: ldap-app

---

apiVersion: applications.authentik.m.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: ldap/v1alpha1/provider
  labels:
    testing.upbound.io/example-name: name
  name: name
  namespace: crossplane-system
spec:
  forProvider:
    name: ldap-app
    protocolProviderSelector:
      matchLabels:
        testing.upbound.io/example-name: name
    slug: ldap-app
