apiVersion: ldap.authentik.m.crossplane.io/v1alpha1
kind: Source
metadata:
  annotations:
    meta.upbound.io/example-id: ldap/v1alpha1/source
  labels:
    testing.upbound.io/example-name: name
  name: name
  namespace: crossplane-system
spec:
  forProvider:
    baseDn: dn=foo
    bindCn: foo
    bindPasswordSecretRef:
      key: example-key
      name: example-secret
    name: ldap-test
    serverUri: ldaps://1.2.3.4
    slug: ldap-test
