// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/unbounded-tech/provider-authentik/apis/cluster/flows/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Provider.
func (mg *Provider) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BindFlow),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BindFlowRef,
		Selector:     mg.Spec.ForProvider.BindFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BindFlow")
	}
	mg.Spec.ForProvider.BindFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BindFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UnbindFlow),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.UnbindFlowRef,
		Selector:     mg.Spec.ForProvider.UnbindFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.UnbindFlow")
	}
	mg.Spec.ForProvider.UnbindFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.UnbindFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BindFlow),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BindFlowRef,
		Selector:     mg.Spec.InitProvider.BindFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BindFlow")
	}
	mg.Spec.InitProvider.BindFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BindFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.UnbindFlow),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.UnbindFlowRef,
		Selector:     mg.Spec.InitProvider.UnbindFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.UnbindFlow")
	}
	mg.Spec.InitProvider.UnbindFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.UnbindFlowRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Source.
func (mg *Source) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PropertyMappings),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.PropertyMappingsRefs,
		Selector:      mg.Spec.ForProvider.PropertyMappingsSelector,
		To: reference.To{
			List:    &SourcePropertyMappingList{},
			Managed: &SourcePropertyMapping{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PropertyMappings")
	}
	mg.Spec.ForProvider.PropertyMappings = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PropertyMappingsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PropertyMappingsGroup),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.PropertyMappingsGroupRefs,
		Selector:      mg.Spec.ForProvider.PropertyMappingsGroupSelector,
		To: reference.To{
			List:    &SourcePropertyMappingList{},
			Managed: &SourcePropertyMapping{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PropertyMappingsGroup")
	}
	mg.Spec.ForProvider.PropertyMappingsGroup = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PropertyMappingsGroupRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PropertyMappings),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.PropertyMappingsRefs,
		Selector:      mg.Spec.InitProvider.PropertyMappingsSelector,
		To: reference.To{
			List:    &SourcePropertyMappingList{},
			Managed: &SourcePropertyMapping{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PropertyMappings")
	}
	mg.Spec.InitProvider.PropertyMappings = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PropertyMappingsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PropertyMappingsGroup),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.PropertyMappingsGroupRefs,
		Selector:      mg.Spec.InitProvider.PropertyMappingsGroupSelector,
		To: reference.To{
			List:    &SourcePropertyMappingList{},
			Managed: &SourcePropertyMapping{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PropertyMappingsGroup")
	}
	mg.Spec.InitProvider.PropertyMappingsGroup = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PropertyMappingsGroupRefs = mrsp.ResolvedReferences

	return nil
}
