// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ProviderInitParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/flows/v1alpha1.Flow
	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// Reference to a Flow in flows to populate authorizationFlow.
	// +kubebuilder:validation:Optional
	AuthorizationFlowRef *v1.NamespacedReference `json:"authorizationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate authorizationFlow.
	// +kubebuilder:validation:Optional
	AuthorizationFlowSelector *v1.NamespacedSelector `json:"authorizationFlowSelector,omitempty" tf:"-"`

	// (String) Defaults to 0.0.0.0/0, ::/0.
	// Defaults to `0.0.0.0/0, ::/0`.
	ClientNetworks *string `json:"clientNetworks,omitempty" tf:"client_networks,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/flows/v1alpha1.Flow
	InvalidationFlow *string `json:"invalidationFlow,omitempty" tf:"invalidation_flow,omitempty"`

	// Reference to a Flow in flows to populate invalidationFlow.
	// +kubebuilder:validation:Optional
	InvalidationFlowRef *v1.NamespacedReference `json:"invalidationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate invalidationFlow.
	// +kubebuilder:validation:Optional
	InvalidationFlowSelector *v1.NamespacedSelector `json:"invalidationFlowSelector,omitempty" tf:"-"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	MfaSupport *bool `json:"mfaSupport,omitempty" tf:"mfa_support,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/radius/v1alpha1.ProviderPropertyMapping
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// References to ProviderPropertyMapping in radius to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsRefs []v1.NamespacedReference `json:"propertyMappingsRefs,omitempty" tf:"-"`

	// Selector for a list of ProviderPropertyMapping in radius to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsSelector *v1.NamespacedSelector `json:"propertyMappingsSelector,omitempty" tf:"-"`

	// (String, Sensitive)
	SharedSecretSecretRef v1.LocalSecretKeySelector `json:"sharedSecretSecretRef" tf:"-"`
}

type ProviderObservation struct {

	// (String)
	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// (String) Defaults to 0.0.0.0/0, ::/0.
	// Defaults to `0.0.0.0/0, ::/0`.
	ClientNetworks *string `json:"clientNetworks,omitempty" tf:"client_networks,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	InvalidationFlow *string `json:"invalidationFlow,omitempty" tf:"invalidation_flow,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	MfaSupport *bool `json:"mfaSupport,omitempty" tf:"mfa_support,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`
}

type ProviderParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/flows/v1alpha1.Flow
	// +kubebuilder:validation:Optional
	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// Reference to a Flow in flows to populate authorizationFlow.
	// +kubebuilder:validation:Optional
	AuthorizationFlowRef *v1.NamespacedReference `json:"authorizationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate authorizationFlow.
	// +kubebuilder:validation:Optional
	AuthorizationFlowSelector *v1.NamespacedSelector `json:"authorizationFlowSelector,omitempty" tf:"-"`

	// (String) Defaults to 0.0.0.0/0, ::/0.
	// Defaults to `0.0.0.0/0, ::/0`.
	// +kubebuilder:validation:Optional
	ClientNetworks *string `json:"clientNetworks,omitempty" tf:"client_networks,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/flows/v1alpha1.Flow
	// +kubebuilder:validation:Optional
	InvalidationFlow *string `json:"invalidationFlow,omitempty" tf:"invalidation_flow,omitempty"`

	// Reference to a Flow in flows to populate invalidationFlow.
	// +kubebuilder:validation:Optional
	InvalidationFlowRef *v1.NamespacedReference `json:"invalidationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate invalidationFlow.
	// +kubebuilder:validation:Optional
	InvalidationFlowSelector *v1.NamespacedSelector `json:"invalidationFlowSelector,omitempty" tf:"-"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	MfaSupport *bool `json:"mfaSupport,omitempty" tf:"mfa_support,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/namespaced/radius/v1alpha1.ProviderPropertyMapping
	// +kubebuilder:validation:Optional
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// References to ProviderPropertyMapping in radius to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsRefs []v1.NamespacedReference `json:"propertyMappingsRefs,omitempty" tf:"-"`

	// Selector for a list of ProviderPropertyMapping in radius to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsSelector *v1.NamespacedSelector `json:"propertyMappingsSelector,omitempty" tf:"-"`

	// (String, Sensitive)
	// +kubebuilder:validation:Optional
	SharedSecretSecretRef v1.LocalSecretKeySelector `json:"sharedSecretSecretRef" tf:"-"`
}

// ProviderSpec defines the desired state of Provider
type ProviderSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProviderParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProviderInitParameters `json:"initProvider,omitempty"`
}

// ProviderStatus defines the observed state of Provider.
type ProviderStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProviderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Provider is the Schema for the Providers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,authentik}
type Provider struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sharedSecretSecretRef)",message="spec.forProvider.sharedSecretSecretRef is a required parameter"
	Spec   ProviderSpec   `json:"spec"`
	Status ProviderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProviderList contains a list of Providers
type ProviderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Provider `json:"items"`
}

// Repository type metadata.
var (
	Provider_Kind             = "Provider"
	Provider_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Provider_Kind}.String()
	Provider_KindAPIVersion   = Provider_Kind + "." + CRDGroupVersion.String()
	Provider_GroupVersionKind = CRDGroupVersion.WithKind(Provider_Kind)
)

func init() {
	SchemeBuilder.Register(&Provider{}, &ProviderList{})
}
