// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/unbounded-tech/provider-authentik/apis/cluster/flows/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Provider.
func (mg *Provider) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AuthorizationFlow),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AuthorizationFlowRef,
		Selector:     mg.Spec.ForProvider.AuthorizationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AuthorizationFlow")
	}
	mg.Spec.ForProvider.AuthorizationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AuthorizationFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.InvalidationFlow),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.InvalidationFlowRef,
		Selector:     mg.Spec.ForProvider.InvalidationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.InvalidationFlow")
	}
	mg.Spec.ForProvider.InvalidationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.InvalidationFlowRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PropertyMappings),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.PropertyMappingsRefs,
		Selector:      mg.Spec.ForProvider.PropertyMappingsSelector,
		To: reference.To{
			List:    &ProviderPropertyMappingList{},
			Managed: &ProviderPropertyMapping{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PropertyMappings")
	}
	mg.Spec.ForProvider.PropertyMappings = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PropertyMappingsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AuthorizationFlow),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AuthorizationFlowRef,
		Selector:     mg.Spec.InitProvider.AuthorizationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AuthorizationFlow")
	}
	mg.Spec.InitProvider.AuthorizationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AuthorizationFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.InvalidationFlow),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.InvalidationFlowRef,
		Selector:     mg.Spec.InitProvider.InvalidationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.InvalidationFlow")
	}
	mg.Spec.InitProvider.InvalidationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.InvalidationFlowRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PropertyMappings),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.PropertyMappingsRefs,
		Selector:      mg.Spec.InitProvider.PropertyMappingsSelector,
		To: reference.To{
			List:    &ProviderPropertyMappingList{},
			Managed: &ProviderPropertyMapping{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PropertyMappings")
	}
	mg.Spec.InitProvider.PropertyMappings = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PropertyMappingsRefs = mrsp.ResolvedReferences

	return nil
}
