//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Provider) DeepCopyInto(out *Provider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Provider.
func (in *Provider) DeepCopy() *Provider {
	if in == nil {
		return nil
	}
	out := new(Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Provider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderInitParameters) DeepCopyInto(out *ProviderInitParameters) {
	*out = *in
	if in.BaseDn != nil {
		in, out := &in.BaseDn, &out.BaseDn
		*out = new(string)
		**out = **in
	}
	if in.BindFlow != nil {
		in, out := &in.BindFlow, &out.BindFlow
		*out = new(string)
		**out = **in
	}
	if in.BindFlowRef != nil {
		in, out := &in.BindFlowRef, &out.BindFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.BindFlowSelector != nil {
		in, out := &in.BindFlowSelector, &out.BindFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BindMode != nil {
		in, out := &in.BindMode, &out.BindMode
		*out = new(string)
		**out = **in
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(string)
		**out = **in
	}
	if in.GIDStartNumber != nil {
		in, out := &in.GIDStartNumber, &out.GIDStartNumber
		*out = new(float64)
		**out = **in
	}
	if in.MfaSupport != nil {
		in, out := &in.MfaSupport, &out.MfaSupport
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SearchMode != nil {
		in, out := &in.SearchMode, &out.SearchMode
		*out = new(string)
		**out = **in
	}
	if in.TLSServerName != nil {
		in, out := &in.TLSServerName, &out.TLSServerName
		*out = new(string)
		**out = **in
	}
	if in.UIDStartNumber != nil {
		in, out := &in.UIDStartNumber, &out.UIDStartNumber
		*out = new(float64)
		**out = **in
	}
	if in.UnbindFlow != nil {
		in, out := &in.UnbindFlow, &out.UnbindFlow
		*out = new(string)
		**out = **in
	}
	if in.UnbindFlowRef != nil {
		in, out := &in.UnbindFlowRef, &out.UnbindFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.UnbindFlowSelector != nil {
		in, out := &in.UnbindFlowSelector, &out.UnbindFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderInitParameters.
func (in *ProviderInitParameters) DeepCopy() *ProviderInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderList) DeepCopyInto(out *ProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Provider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderList.
func (in *ProviderList) DeepCopy() *ProviderList {
	if in == nil {
		return nil
	}
	out := new(ProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderObservation) DeepCopyInto(out *ProviderObservation) {
	*out = *in
	if in.BaseDn != nil {
		in, out := &in.BaseDn, &out.BaseDn
		*out = new(string)
		**out = **in
	}
	if in.BindFlow != nil {
		in, out := &in.BindFlow, &out.BindFlow
		*out = new(string)
		**out = **in
	}
	if in.BindMode != nil {
		in, out := &in.BindMode, &out.BindMode
		*out = new(string)
		**out = **in
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(string)
		**out = **in
	}
	if in.GIDStartNumber != nil {
		in, out := &in.GIDStartNumber, &out.GIDStartNumber
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MfaSupport != nil {
		in, out := &in.MfaSupport, &out.MfaSupport
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SearchMode != nil {
		in, out := &in.SearchMode, &out.SearchMode
		*out = new(string)
		**out = **in
	}
	if in.TLSServerName != nil {
		in, out := &in.TLSServerName, &out.TLSServerName
		*out = new(string)
		**out = **in
	}
	if in.UIDStartNumber != nil {
		in, out := &in.UIDStartNumber, &out.UIDStartNumber
		*out = new(float64)
		**out = **in
	}
	if in.UnbindFlow != nil {
		in, out := &in.UnbindFlow, &out.UnbindFlow
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderObservation.
func (in *ProviderObservation) DeepCopy() *ProviderObservation {
	if in == nil {
		return nil
	}
	out := new(ProviderObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderParameters) DeepCopyInto(out *ProviderParameters) {
	*out = *in
	if in.BaseDn != nil {
		in, out := &in.BaseDn, &out.BaseDn
		*out = new(string)
		**out = **in
	}
	if in.BindFlow != nil {
		in, out := &in.BindFlow, &out.BindFlow
		*out = new(string)
		**out = **in
	}
	if in.BindFlowRef != nil {
		in, out := &in.BindFlowRef, &out.BindFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.BindFlowSelector != nil {
		in, out := &in.BindFlowSelector, &out.BindFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BindMode != nil {
		in, out := &in.BindMode, &out.BindMode
		*out = new(string)
		**out = **in
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(string)
		**out = **in
	}
	if in.GIDStartNumber != nil {
		in, out := &in.GIDStartNumber, &out.GIDStartNumber
		*out = new(float64)
		**out = **in
	}
	if in.MfaSupport != nil {
		in, out := &in.MfaSupport, &out.MfaSupport
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SearchMode != nil {
		in, out := &in.SearchMode, &out.SearchMode
		*out = new(string)
		**out = **in
	}
	if in.TLSServerName != nil {
		in, out := &in.TLSServerName, &out.TLSServerName
		*out = new(string)
		**out = **in
	}
	if in.UIDStartNumber != nil {
		in, out := &in.UIDStartNumber, &out.UIDStartNumber
		*out = new(float64)
		**out = **in
	}
	if in.UnbindFlow != nil {
		in, out := &in.UnbindFlow, &out.UnbindFlow
		*out = new(string)
		**out = **in
	}
	if in.UnbindFlowRef != nil {
		in, out := &in.UnbindFlowRef, &out.UnbindFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.UnbindFlowSelector != nil {
		in, out := &in.UnbindFlowSelector, &out.UnbindFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderParameters.
func (in *ProviderParameters) DeepCopy() *ProviderParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSpec) DeepCopyInto(out *ProviderSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSpec.
func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderStatus) DeepCopyInto(out *ProviderStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderStatus.
func (in *ProviderStatus) DeepCopy() *ProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Source) DeepCopyInto(out *Source) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Source.
func (in *Source) DeepCopy() *Source {
	if in == nil {
		return nil
	}
	out := new(Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Source) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceInitParameters) DeepCopyInto(out *SourceInitParameters) {
	*out = *in
	if in.AdditionalGroupDn != nil {
		in, out := &in.AdditionalGroupDn, &out.AdditionalGroupDn
		*out = new(string)
		**out = **in
	}
	if in.AdditionalUserDn != nil {
		in, out := &in.AdditionalUserDn, &out.AdditionalUserDn
		*out = new(string)
		**out = **in
	}
	if in.BaseDn != nil {
		in, out := &in.BaseDn, &out.BaseDn
		*out = new(string)
		**out = **in
	}
	if in.BindCn != nil {
		in, out := &in.BindCn, &out.BindCn
		*out = new(string)
		**out = **in
	}
	in.BindPasswordSecretRef.DeepCopyInto(&out.BindPasswordSecretRef)
	if in.DeleteNotFoundObjects != nil {
		in, out := &in.DeleteNotFoundObjects, &out.DeleteNotFoundObjects
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupMembershipField != nil {
		in, out := &in.GroupMembershipField, &out.GroupMembershipField
		*out = new(string)
		**out = **in
	}
	if in.GroupObjectFilter != nil {
		in, out := &in.GroupObjectFilter, &out.GroupObjectFilter
		*out = new(string)
		**out = **in
	}
	if in.LookupGroupsFromUser != nil {
		in, out := &in.LookupGroupsFromUser, &out.LookupGroupsFromUser
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ObjectUniquenessField != nil {
		in, out := &in.ObjectUniquenessField, &out.ObjectUniquenessField
		*out = new(string)
		**out = **in
	}
	if in.PasswordLoginUpdateInternalPassword != nil {
		in, out := &in.PasswordLoginUpdateInternalPassword, &out.PasswordLoginUpdateInternalPassword
		*out = new(bool)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroupRefs != nil {
		in, out := &in.PropertyMappingsGroupRefs, &out.PropertyMappingsGroupRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsGroupSelector != nil {
		in, out := &in.PropertyMappingsGroupSelector, &out.PropertyMappingsGroupSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PropertyMappingsRefs != nil {
		in, out := &in.PropertyMappingsRefs, &out.PropertyMappingsRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsSelector != nil {
		in, out := &in.PropertyMappingsSelector, &out.PropertyMappingsSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerURI != nil {
		in, out := &in.ServerURI, &out.ServerURI
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.Sni != nil {
		in, out := &in.Sni, &out.Sni
		*out = new(bool)
		**out = **in
	}
	if in.StartTLS != nil {
		in, out := &in.StartTLS, &out.StartTLS
		*out = new(bool)
		**out = **in
	}
	if in.SyncGroups != nil {
		in, out := &in.SyncGroups, &out.SyncGroups
		*out = new(bool)
		**out = **in
	}
	if in.SyncParentGroup != nil {
		in, out := &in.SyncParentGroup, &out.SyncParentGroup
		*out = new(string)
		**out = **in
	}
	if in.SyncUsers != nil {
		in, out := &in.SyncUsers, &out.SyncUsers
		*out = new(bool)
		**out = **in
	}
	if in.SyncUsersPassword != nil {
		in, out := &in.SyncUsersPassword, &out.SyncUsersPassword
		*out = new(bool)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMembershipAttribute != nil {
		in, out := &in.UserMembershipAttribute, &out.UserMembershipAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserObjectFilter != nil {
		in, out := &in.UserObjectFilter, &out.UserObjectFilter
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceInitParameters.
func (in *SourceInitParameters) DeepCopy() *SourceInitParameters {
	if in == nil {
		return nil
	}
	out := new(SourceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceList) DeepCopyInto(out *SourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Source, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceList.
func (in *SourceList) DeepCopy() *SourceList {
	if in == nil {
		return nil
	}
	out := new(SourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceObservation) DeepCopyInto(out *SourceObservation) {
	*out = *in
	if in.AdditionalGroupDn != nil {
		in, out := &in.AdditionalGroupDn, &out.AdditionalGroupDn
		*out = new(string)
		**out = **in
	}
	if in.AdditionalUserDn != nil {
		in, out := &in.AdditionalUserDn, &out.AdditionalUserDn
		*out = new(string)
		**out = **in
	}
	if in.BaseDn != nil {
		in, out := &in.BaseDn, &out.BaseDn
		*out = new(string)
		**out = **in
	}
	if in.BindCn != nil {
		in, out := &in.BindCn, &out.BindCn
		*out = new(string)
		**out = **in
	}
	if in.DeleteNotFoundObjects != nil {
		in, out := &in.DeleteNotFoundObjects, &out.DeleteNotFoundObjects
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupMembershipField != nil {
		in, out := &in.GroupMembershipField, &out.GroupMembershipField
		*out = new(string)
		**out = **in
	}
	if in.GroupObjectFilter != nil {
		in, out := &in.GroupObjectFilter, &out.GroupObjectFilter
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LookupGroupsFromUser != nil {
		in, out := &in.LookupGroupsFromUser, &out.LookupGroupsFromUser
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ObjectUniquenessField != nil {
		in, out := &in.ObjectUniquenessField, &out.ObjectUniquenessField
		*out = new(string)
		**out = **in
	}
	if in.PasswordLoginUpdateInternalPassword != nil {
		in, out := &in.PasswordLoginUpdateInternalPassword, &out.PasswordLoginUpdateInternalPassword
		*out = new(bool)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ServerURI != nil {
		in, out := &in.ServerURI, &out.ServerURI
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.Sni != nil {
		in, out := &in.Sni, &out.Sni
		*out = new(bool)
		**out = **in
	}
	if in.StartTLS != nil {
		in, out := &in.StartTLS, &out.StartTLS
		*out = new(bool)
		**out = **in
	}
	if in.SyncGroups != nil {
		in, out := &in.SyncGroups, &out.SyncGroups
		*out = new(bool)
		**out = **in
	}
	if in.SyncParentGroup != nil {
		in, out := &in.SyncParentGroup, &out.SyncParentGroup
		*out = new(string)
		**out = **in
	}
	if in.SyncUsers != nil {
		in, out := &in.SyncUsers, &out.SyncUsers
		*out = new(bool)
		**out = **in
	}
	if in.SyncUsersPassword != nil {
		in, out := &in.SyncUsersPassword, &out.SyncUsersPassword
		*out = new(bool)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMembershipAttribute != nil {
		in, out := &in.UserMembershipAttribute, &out.UserMembershipAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserObjectFilter != nil {
		in, out := &in.UserObjectFilter, &out.UserObjectFilter
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceObservation.
func (in *SourceObservation) DeepCopy() *SourceObservation {
	if in == nil {
		return nil
	}
	out := new(SourceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceParameters) DeepCopyInto(out *SourceParameters) {
	*out = *in
	if in.AdditionalGroupDn != nil {
		in, out := &in.AdditionalGroupDn, &out.AdditionalGroupDn
		*out = new(string)
		**out = **in
	}
	if in.AdditionalUserDn != nil {
		in, out := &in.AdditionalUserDn, &out.AdditionalUserDn
		*out = new(string)
		**out = **in
	}
	if in.BaseDn != nil {
		in, out := &in.BaseDn, &out.BaseDn
		*out = new(string)
		**out = **in
	}
	if in.BindCn != nil {
		in, out := &in.BindCn, &out.BindCn
		*out = new(string)
		**out = **in
	}
	in.BindPasswordSecretRef.DeepCopyInto(&out.BindPasswordSecretRef)
	if in.DeleteNotFoundObjects != nil {
		in, out := &in.DeleteNotFoundObjects, &out.DeleteNotFoundObjects
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupMembershipField != nil {
		in, out := &in.GroupMembershipField, &out.GroupMembershipField
		*out = new(string)
		**out = **in
	}
	if in.GroupObjectFilter != nil {
		in, out := &in.GroupObjectFilter, &out.GroupObjectFilter
		*out = new(string)
		**out = **in
	}
	if in.LookupGroupsFromUser != nil {
		in, out := &in.LookupGroupsFromUser, &out.LookupGroupsFromUser
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ObjectUniquenessField != nil {
		in, out := &in.ObjectUniquenessField, &out.ObjectUniquenessField
		*out = new(string)
		**out = **in
	}
	if in.PasswordLoginUpdateInternalPassword != nil {
		in, out := &in.PasswordLoginUpdateInternalPassword, &out.PasswordLoginUpdateInternalPassword
		*out = new(bool)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroupRefs != nil {
		in, out := &in.PropertyMappingsGroupRefs, &out.PropertyMappingsGroupRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsGroupSelector != nil {
		in, out := &in.PropertyMappingsGroupSelector, &out.PropertyMappingsGroupSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PropertyMappingsRefs != nil {
		in, out := &in.PropertyMappingsRefs, &out.PropertyMappingsRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsSelector != nil {
		in, out := &in.PropertyMappingsSelector, &out.PropertyMappingsSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerURI != nil {
		in, out := &in.ServerURI, &out.ServerURI
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.Sni != nil {
		in, out := &in.Sni, &out.Sni
		*out = new(bool)
		**out = **in
	}
	if in.StartTLS != nil {
		in, out := &in.StartTLS, &out.StartTLS
		*out = new(bool)
		**out = **in
	}
	if in.SyncGroups != nil {
		in, out := &in.SyncGroups, &out.SyncGroups
		*out = new(bool)
		**out = **in
	}
	if in.SyncParentGroup != nil {
		in, out := &in.SyncParentGroup, &out.SyncParentGroup
		*out = new(string)
		**out = **in
	}
	if in.SyncUsers != nil {
		in, out := &in.SyncUsers, &out.SyncUsers
		*out = new(bool)
		**out = **in
	}
	if in.SyncUsersPassword != nil {
		in, out := &in.SyncUsersPassword, &out.SyncUsersPassword
		*out = new(bool)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMembershipAttribute != nil {
		in, out := &in.UserMembershipAttribute, &out.UserMembershipAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserObjectFilter != nil {
		in, out := &in.UserObjectFilter, &out.UserObjectFilter
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceParameters.
func (in *SourceParameters) DeepCopy() *SourceParameters {
	if in == nil {
		return nil
	}
	out := new(SourceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePropertyMapping) DeepCopyInto(out *SourcePropertyMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePropertyMapping.
func (in *SourcePropertyMapping) DeepCopy() *SourcePropertyMapping {
	if in == nil {
		return nil
	}
	out := new(SourcePropertyMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourcePropertyMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePropertyMappingInitParameters) DeepCopyInto(out *SourcePropertyMappingInitParameters) {
	*out = *in
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePropertyMappingInitParameters.
func (in *SourcePropertyMappingInitParameters) DeepCopy() *SourcePropertyMappingInitParameters {
	if in == nil {
		return nil
	}
	out := new(SourcePropertyMappingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePropertyMappingList) DeepCopyInto(out *SourcePropertyMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SourcePropertyMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePropertyMappingList.
func (in *SourcePropertyMappingList) DeepCopy() *SourcePropertyMappingList {
	if in == nil {
		return nil
	}
	out := new(SourcePropertyMappingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourcePropertyMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePropertyMappingObservation) DeepCopyInto(out *SourcePropertyMappingObservation) {
	*out = *in
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePropertyMappingObservation.
func (in *SourcePropertyMappingObservation) DeepCopy() *SourcePropertyMappingObservation {
	if in == nil {
		return nil
	}
	out := new(SourcePropertyMappingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePropertyMappingParameters) DeepCopyInto(out *SourcePropertyMappingParameters) {
	*out = *in
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePropertyMappingParameters.
func (in *SourcePropertyMappingParameters) DeepCopy() *SourcePropertyMappingParameters {
	if in == nil {
		return nil
	}
	out := new(SourcePropertyMappingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePropertyMappingSpec) DeepCopyInto(out *SourcePropertyMappingSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePropertyMappingSpec.
func (in *SourcePropertyMappingSpec) DeepCopy() *SourcePropertyMappingSpec {
	if in == nil {
		return nil
	}
	out := new(SourcePropertyMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePropertyMappingStatus) DeepCopyInto(out *SourcePropertyMappingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePropertyMappingStatus.
func (in *SourcePropertyMappingStatus) DeepCopy() *SourcePropertyMappingStatus {
	if in == nil {
		return nil
	}
	out := new(SourcePropertyMappingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSpec) DeepCopyInto(out *SourceSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSpec.
func (in *SourceSpec) DeepCopy() *SourceSpec {
	if in == nil {
		return nil
	}
	out := new(SourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceStatus) DeepCopyInto(out *SourceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceStatus.
func (in *SourceStatus) DeepCopy() *SourceStatus {
	if in == nil {
		return nil
	}
	out := new(SourceStatus)
	in.DeepCopyInto(out)
	return out
}
