apiVersion: stages.authentik.m.crossplane.io/v1alpha1
kind: PromptField
metadata:
  annotations:
    meta.upbound.io/example-id: stages/v1alpha1/promptfield
  labels:
    testing.upbound.io/example-name: field
  name: field
  namespace: crossplane-system
spec:
  forProvider:
    fieldKey: username
    label: Username
    name: username
    type: username
