//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Provider) DeepCopyInto(out *Provider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Provider.
func (in *Provider) DeepCopy() *Provider {
	if in == nil {
		return nil
	}
	out := new(Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Provider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderInitParameters) DeepCopyInto(out *ProviderInitParameters) {
	*out = *in
	if in.AccessCodeValidity != nil {
		in, out := &in.AccessCodeValidity, &out.AccessCodeValidity
		*out = new(string)
		**out = **in
	}
	if in.AccessTokenValidity != nil {
		in, out := &in.AccessTokenValidity, &out.AccessTokenValidity
		*out = new(string)
		**out = **in
	}
	if in.AllowedRedirectUris != nil {
		in, out := &in.AllowedRedirectUris, &out.AllowedRedirectUris
		*out = make([]map[string]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]*string, len(*in))
				for key, val := range *in {
					var outVal *string
					if val == nil {
						(*out)[key] = nil
					} else {
						inVal := (*in)[key]
						in, out := &inVal, &outVal
						*out = new(string)
						**out = **in
					}
					(*out)[key] = outVal
				}
			}
		}
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorizationFlow != nil {
		in, out := &in.AuthorizationFlow, &out.AuthorizationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationFlowRef != nil {
		in, out := &in.AuthorizationFlowRef, &out.AuthorizationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorizationFlowSelector != nil {
		in, out := &in.AuthorizationFlowSelector, &out.AuthorizationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ClientSecretSecretRef != nil {
		in, out := &in.ClientSecretSecretRef, &out.ClientSecretSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.ClientType != nil {
		in, out := &in.ClientType, &out.ClientType
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKey != nil {
		in, out := &in.EncryptionKey, &out.EncryptionKey
		*out = new(string)
		**out = **in
	}
	if in.IncludeClaimsInIDToken != nil {
		in, out := &in.IncludeClaimsInIDToken, &out.IncludeClaimsInIDToken
		*out = new(bool)
		**out = **in
	}
	if in.InvalidationFlow != nil {
		in, out := &in.InvalidationFlow, &out.InvalidationFlow
		*out = new(string)
		**out = **in
	}
	if in.InvalidationFlowRef != nil {
		in, out := &in.InvalidationFlowRef, &out.InvalidationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.InvalidationFlowSelector != nil {
		in, out := &in.InvalidationFlowSelector, &out.InvalidationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.IssuerMode != nil {
		in, out := &in.IssuerMode, &out.IssuerMode
		*out = new(string)
		**out = **in
	}
	if in.JwksSources != nil {
		in, out := &in.JwksSources, &out.JwksSources
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.JwtFederationProviders != nil {
		in, out := &in.JwtFederationProviders, &out.JwtFederationProviders
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.JwtFederationProvidersRefs != nil {
		in, out := &in.JwtFederationProvidersRefs, &out.JwtFederationProvidersRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.JwtFederationProvidersSelector != nil {
		in, out := &in.JwtFederationProvidersSelector, &out.JwtFederationProvidersSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.JwtFederationSources != nil {
		in, out := &in.JwtFederationSources, &out.JwtFederationSources
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LogoutMethod != nil {
		in, out := &in.LogoutMethod, &out.LogoutMethod
		*out = new(string)
		**out = **in
	}
	if in.LogoutURI != nil {
		in, out := &in.LogoutURI, &out.LogoutURI
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsRefs != nil {
		in, out := &in.PropertyMappingsRefs, &out.PropertyMappingsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsSelector != nil {
		in, out := &in.PropertyMappingsSelector, &out.PropertyMappingsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RefreshTokenThreshold != nil {
		in, out := &in.RefreshTokenThreshold, &out.RefreshTokenThreshold
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenValidity != nil {
		in, out := &in.RefreshTokenValidity, &out.RefreshTokenValidity
		*out = new(string)
		**out = **in
	}
	if in.SigningKey != nil {
		in, out := &in.SigningKey, &out.SigningKey
		*out = new(string)
		**out = **in
	}
	if in.SigningKeyRef != nil {
		in, out := &in.SigningKeyRef, &out.SigningKeyRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SigningKeySelector != nil {
		in, out := &in.SigningKeySelector, &out.SigningKeySelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SubMode != nil {
		in, out := &in.SubMode, &out.SubMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderInitParameters.
func (in *ProviderInitParameters) DeepCopy() *ProviderInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderList) DeepCopyInto(out *ProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Provider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderList.
func (in *ProviderList) DeepCopy() *ProviderList {
	if in == nil {
		return nil
	}
	out := new(ProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderObservation) DeepCopyInto(out *ProviderObservation) {
	*out = *in
	if in.AccessCodeValidity != nil {
		in, out := &in.AccessCodeValidity, &out.AccessCodeValidity
		*out = new(string)
		**out = **in
	}
	if in.AccessTokenValidity != nil {
		in, out := &in.AccessTokenValidity, &out.AccessTokenValidity
		*out = new(string)
		**out = **in
	}
	if in.AllowedRedirectUris != nil {
		in, out := &in.AllowedRedirectUris, &out.AllowedRedirectUris
		*out = make([]map[string]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]*string, len(*in))
				for key, val := range *in {
					var outVal *string
					if val == nil {
						(*out)[key] = nil
					} else {
						inVal := (*in)[key]
						in, out := &inVal, &outVal
						*out = new(string)
						**out = **in
					}
					(*out)[key] = outVal
				}
			}
		}
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationFlow != nil {
		in, out := &in.AuthorizationFlow, &out.AuthorizationFlow
		*out = new(string)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ClientType != nil {
		in, out := &in.ClientType, &out.ClientType
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKey != nil {
		in, out := &in.EncryptionKey, &out.EncryptionKey
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IncludeClaimsInIDToken != nil {
		in, out := &in.IncludeClaimsInIDToken, &out.IncludeClaimsInIDToken
		*out = new(bool)
		**out = **in
	}
	if in.InvalidationFlow != nil {
		in, out := &in.InvalidationFlow, &out.InvalidationFlow
		*out = new(string)
		**out = **in
	}
	if in.IssuerMode != nil {
		in, out := &in.IssuerMode, &out.IssuerMode
		*out = new(string)
		**out = **in
	}
	if in.JwksSources != nil {
		in, out := &in.JwksSources, &out.JwksSources
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.JwtFederationProviders != nil {
		in, out := &in.JwtFederationProviders, &out.JwtFederationProviders
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.JwtFederationSources != nil {
		in, out := &in.JwtFederationSources, &out.JwtFederationSources
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LogoutMethod != nil {
		in, out := &in.LogoutMethod, &out.LogoutMethod
		*out = new(string)
		**out = **in
	}
	if in.LogoutURI != nil {
		in, out := &in.LogoutURI, &out.LogoutURI
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RefreshTokenThreshold != nil {
		in, out := &in.RefreshTokenThreshold, &out.RefreshTokenThreshold
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenValidity != nil {
		in, out := &in.RefreshTokenValidity, &out.RefreshTokenValidity
		*out = new(string)
		**out = **in
	}
	if in.SigningKey != nil {
		in, out := &in.SigningKey, &out.SigningKey
		*out = new(string)
		**out = **in
	}
	if in.SubMode != nil {
		in, out := &in.SubMode, &out.SubMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderObservation.
func (in *ProviderObservation) DeepCopy() *ProviderObservation {
	if in == nil {
		return nil
	}
	out := new(ProviderObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderParameters) DeepCopyInto(out *ProviderParameters) {
	*out = *in
	if in.AccessCodeValidity != nil {
		in, out := &in.AccessCodeValidity, &out.AccessCodeValidity
		*out = new(string)
		**out = **in
	}
	if in.AccessTokenValidity != nil {
		in, out := &in.AccessTokenValidity, &out.AccessTokenValidity
		*out = new(string)
		**out = **in
	}
	if in.AllowedRedirectUris != nil {
		in, out := &in.AllowedRedirectUris, &out.AllowedRedirectUris
		*out = make([]map[string]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]*string, len(*in))
				for key, val := range *in {
					var outVal *string
					if val == nil {
						(*out)[key] = nil
					} else {
						inVal := (*in)[key]
						in, out := &inVal, &outVal
						*out = new(string)
						**out = **in
					}
					(*out)[key] = outVal
				}
			}
		}
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorizationFlow != nil {
		in, out := &in.AuthorizationFlow, &out.AuthorizationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationFlowRef != nil {
		in, out := &in.AuthorizationFlowRef, &out.AuthorizationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorizationFlowSelector != nil {
		in, out := &in.AuthorizationFlowSelector, &out.AuthorizationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ClientSecretSecretRef != nil {
		in, out := &in.ClientSecretSecretRef, &out.ClientSecretSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.ClientType != nil {
		in, out := &in.ClientType, &out.ClientType
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKey != nil {
		in, out := &in.EncryptionKey, &out.EncryptionKey
		*out = new(string)
		**out = **in
	}
	if in.IncludeClaimsInIDToken != nil {
		in, out := &in.IncludeClaimsInIDToken, &out.IncludeClaimsInIDToken
		*out = new(bool)
		**out = **in
	}
	if in.InvalidationFlow != nil {
		in, out := &in.InvalidationFlow, &out.InvalidationFlow
		*out = new(string)
		**out = **in
	}
	if in.InvalidationFlowRef != nil {
		in, out := &in.InvalidationFlowRef, &out.InvalidationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.InvalidationFlowSelector != nil {
		in, out := &in.InvalidationFlowSelector, &out.InvalidationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.IssuerMode != nil {
		in, out := &in.IssuerMode, &out.IssuerMode
		*out = new(string)
		**out = **in
	}
	if in.JwksSources != nil {
		in, out := &in.JwksSources, &out.JwksSources
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.JwtFederationProviders != nil {
		in, out := &in.JwtFederationProviders, &out.JwtFederationProviders
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.JwtFederationProvidersRefs != nil {
		in, out := &in.JwtFederationProvidersRefs, &out.JwtFederationProvidersRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.JwtFederationProvidersSelector != nil {
		in, out := &in.JwtFederationProvidersSelector, &out.JwtFederationProvidersSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.JwtFederationSources != nil {
		in, out := &in.JwtFederationSources, &out.JwtFederationSources
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LogoutMethod != nil {
		in, out := &in.LogoutMethod, &out.LogoutMethod
		*out = new(string)
		**out = **in
	}
	if in.LogoutURI != nil {
		in, out := &in.LogoutURI, &out.LogoutURI
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsRefs != nil {
		in, out := &in.PropertyMappingsRefs, &out.PropertyMappingsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsSelector != nil {
		in, out := &in.PropertyMappingsSelector, &out.PropertyMappingsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RefreshTokenThreshold != nil {
		in, out := &in.RefreshTokenThreshold, &out.RefreshTokenThreshold
		*out = new(string)
		**out = **in
	}
	if in.RefreshTokenValidity != nil {
		in, out := &in.RefreshTokenValidity, &out.RefreshTokenValidity
		*out = new(string)
		**out = **in
	}
	if in.SigningKey != nil {
		in, out := &in.SigningKey, &out.SigningKey
		*out = new(string)
		**out = **in
	}
	if in.SigningKeyRef != nil {
		in, out := &in.SigningKeyRef, &out.SigningKeyRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SigningKeySelector != nil {
		in, out := &in.SigningKeySelector, &out.SigningKeySelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SubMode != nil {
		in, out := &in.SubMode, &out.SubMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderParameters.
func (in *ProviderParameters) DeepCopy() *ProviderParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSpec) DeepCopyInto(out *ProviderSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSpec.
func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderStatus) DeepCopyInto(out *ProviderStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderStatus.
func (in *ProviderStatus) DeepCopy() *ProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderStatus)
	in.DeepCopyInto(out)
	return out
}
