// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/unbounded-tech/provider-authentik/apis/namespaced/flows/v1alpha1"
	v1alpha11 "github.com/unbounded-tech/provider-authentik/apis/namespaced/oauth/v1alpha1"
	v1alpha12 "github.com/unbounded-tech/provider-authentik/apis/namespaced/system/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Provider.
func (mg *Provider) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AuthenticationFlow),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AuthenticationFlowRef,
		Selector:     mg.Spec.ForProvider.AuthenticationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AuthenticationFlow")
	}
	mg.Spec.ForProvider.AuthenticationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AuthenticationFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AuthorizationFlow),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AuthorizationFlowRef,
		Selector:     mg.Spec.ForProvider.AuthorizationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AuthorizationFlow")
	}
	mg.Spec.ForProvider.AuthorizationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AuthorizationFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.InvalidationFlow),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.InvalidationFlowRef,
		Selector:     mg.Spec.ForProvider.InvalidationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.InvalidationFlow")
	}
	mg.Spec.ForProvider.InvalidationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.InvalidationFlowRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromFloatPtrValues(mg.Spec.ForProvider.JwtFederationProviders),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.JwtFederationProvidersRefs,
		Selector:      mg.Spec.ForProvider.JwtFederationProvidersSelector,
		To: reference.To{
			List:    &ProviderList{},
			Managed: &Provider{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.JwtFederationProviders")
	}
	mg.Spec.ForProvider.JwtFederationProviders = reference.ToFloatPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.JwtFederationProvidersRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PropertyMappings),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.PropertyMappingsRefs,
		Selector:      mg.Spec.ForProvider.PropertyMappingsSelector,
		To: reference.To{
			List:    &v1alpha11.SourcePropertyMappingList{},
			Managed: &v1alpha11.SourcePropertyMapping{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PropertyMappings")
	}
	mg.Spec.ForProvider.PropertyMappings = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PropertyMappingsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SigningKey),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SigningKeyRef,
		Selector:     mg.Spec.ForProvider.SigningKeySelector,
		To: reference.To{
			List:    &v1alpha12.CertificateKeyPairList{},
			Managed: &v1alpha12.CertificateKeyPair{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SigningKey")
	}
	mg.Spec.ForProvider.SigningKey = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SigningKeyRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AuthenticationFlow),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AuthenticationFlowRef,
		Selector:     mg.Spec.InitProvider.AuthenticationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AuthenticationFlow")
	}
	mg.Spec.InitProvider.AuthenticationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AuthenticationFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AuthorizationFlow),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AuthorizationFlowRef,
		Selector:     mg.Spec.InitProvider.AuthorizationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AuthorizationFlow")
	}
	mg.Spec.InitProvider.AuthorizationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AuthorizationFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.InvalidationFlow),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.InvalidationFlowRef,
		Selector:     mg.Spec.InitProvider.InvalidationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.InvalidationFlow")
	}
	mg.Spec.InitProvider.InvalidationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.InvalidationFlowRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromFloatPtrValues(mg.Spec.InitProvider.JwtFederationProviders),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.JwtFederationProvidersRefs,
		Selector:      mg.Spec.InitProvider.JwtFederationProvidersSelector,
		To: reference.To{
			List:    &ProviderList{},
			Managed: &Provider{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.JwtFederationProviders")
	}
	mg.Spec.InitProvider.JwtFederationProviders = reference.ToFloatPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.JwtFederationProvidersRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PropertyMappings),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.PropertyMappingsRefs,
		Selector:      mg.Spec.InitProvider.PropertyMappingsSelector,
		To: reference.To{
			List:    &v1alpha11.SourcePropertyMappingList{},
			Managed: &v1alpha11.SourcePropertyMapping{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PropertyMappings")
	}
	mg.Spec.InitProvider.PropertyMappings = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PropertyMappingsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SigningKey),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SigningKeyRef,
		Selector:     mg.Spec.InitProvider.SigningKeySelector,
		To: reference.To{
			List:    &v1alpha12.CertificateKeyPairList{},
			Managed: &v1alpha12.CertificateKeyPair{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SigningKey")
	}
	mg.Spec.InitProvider.SigningKey = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SigningKeyRef = rsp.ResolvedReference

	return nil
}
