//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Plex) DeepCopyInto(out *Plex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Plex.
func (in *Plex) DeepCopy() *Plex {
	if in == nil {
		return nil
	}
	out := new(Plex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Plex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexInitParameters) DeepCopyInto(out *PlexInitParameters) {
	*out = *in
	if in.AllowFriends != nil {
		in, out := &in.AllowFriends, &out.AllowFriends
		*out = new(bool)
		**out = **in
	}
	if in.AllowedServers != nil {
		in, out := &in.AllowedServers, &out.AllowedServers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	in.PlexTokenSecretRef.DeepCopyInto(&out.PlexTokenSecretRef)
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexInitParameters.
func (in *PlexInitParameters) DeepCopy() *PlexInitParameters {
	if in == nil {
		return nil
	}
	out := new(PlexInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexList) DeepCopyInto(out *PlexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Plex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexList.
func (in *PlexList) DeepCopy() *PlexList {
	if in == nil {
		return nil
	}
	out := new(PlexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexObservation) DeepCopyInto(out *PlexObservation) {
	*out = *in
	if in.AllowFriends != nil {
		in, out := &in.AllowFriends, &out.AllowFriends
		*out = new(bool)
		**out = **in
	}
	if in.AllowedServers != nil {
		in, out := &in.AllowedServers, &out.AllowedServers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexObservation.
func (in *PlexObservation) DeepCopy() *PlexObservation {
	if in == nil {
		return nil
	}
	out := new(PlexObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexParameters) DeepCopyInto(out *PlexParameters) {
	*out = *in
	if in.AllowFriends != nil {
		in, out := &in.AllowFriends, &out.AllowFriends
		*out = new(bool)
		**out = **in
	}
	if in.AllowedServers != nil {
		in, out := &in.AllowedServers, &out.AllowedServers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	in.PlexTokenSecretRef.DeepCopyInto(&out.PlexTokenSecretRef)
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexParameters.
func (in *PlexParameters) DeepCopy() *PlexParameters {
	if in == nil {
		return nil
	}
	out := new(PlexParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexSpec) DeepCopyInto(out *PlexSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexSpec.
func (in *PlexSpec) DeepCopy() *PlexSpec {
	if in == nil {
		return nil
	}
	out := new(PlexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexStatus) DeepCopyInto(out *PlexStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexStatus.
func (in *PlexStatus) DeepCopy() *PlexStatus {
	if in == nil {
		return nil
	}
	out := new(PlexStatus)
	in.DeepCopyInto(out)
	return out
}
