apiVersion: scim.authentik.crossplane.io/v1alpha1
kind: Provider
metadata:
  annotations:
    meta.upbound.io/example-id: scim/v1alpha1/provider
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: test-app
    propertyMappingsGroupRefs:
    - name: authentik_property_mapping_scim
    propertyMappingsRefs:
    - name: authentik_property_mapping_scim
    tokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    url: http://localhost
