//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Provider) DeepCopyInto(out *Provider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Provider.
func (in *Provider) DeepCopy() *Provider {
	if in == nil {
		return nil
	}
	out := new(Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Provider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderInitParameters) DeepCopyInto(out *ProviderInitParameters) {
	*out = *in
	if in.AcsURL != nil {
		in, out := &in.AcsURL, &out.AcsURL
		*out = new(string)
		**out = **in
	}
	if in.AssertionValidNotBefore != nil {
		in, out := &in.AssertionValidNotBefore, &out.AssertionValidNotBefore
		*out = new(string)
		**out = **in
	}
	if in.AssertionValidNotOnOrAfter != nil {
		in, out := &in.AssertionValidNotOnOrAfter, &out.AssertionValidNotOnOrAfter
		*out = new(string)
		**out = **in
	}
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthnContextClassRefMapping != nil {
		in, out := &in.AuthnContextClassRefMapping, &out.AuthnContextClassRefMapping
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationFlow != nil {
		in, out := &in.AuthorizationFlow, &out.AuthorizationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationFlowRef != nil {
		in, out := &in.AuthorizationFlowRef, &out.AuthorizationFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorizationFlowSelector != nil {
		in, out := &in.AuthorizationFlowSelector, &out.AuthorizationFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultRelayState != nil {
		in, out := &in.DefaultRelayState, &out.DefaultRelayState
		*out = new(string)
		**out = **in
	}
	if in.DigestAlgorithm != nil {
		in, out := &in.DigestAlgorithm, &out.DigestAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKp != nil {
		in, out := &in.EncryptionKp, &out.EncryptionKp
		*out = new(string)
		**out = **in
	}
	if in.InvalidationFlow != nil {
		in, out := &in.InvalidationFlow, &out.InvalidationFlow
		*out = new(string)
		**out = **in
	}
	if in.InvalidationFlowRef != nil {
		in, out := &in.InvalidationFlowRef, &out.InvalidationFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.InvalidationFlowSelector != nil {
		in, out := &in.InvalidationFlowSelector, &out.InvalidationFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDMapping != nil {
		in, out := &in.NameIDMapping, &out.NameIDMapping
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsRefs != nil {
		in, out := &in.PropertyMappingsRefs, &out.PropertyMappingsRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsSelector != nil {
		in, out := &in.PropertyMappingsSelector, &out.PropertyMappingsSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SessionValidNotOnOrAfter != nil {
		in, out := &in.SessionValidNotOnOrAfter, &out.SessionValidNotOnOrAfter
		*out = new(string)
		**out = **in
	}
	if in.SignAssertion != nil {
		in, out := &in.SignAssertion, &out.SignAssertion
		*out = new(bool)
		**out = **in
	}
	if in.SignResponse != nil {
		in, out := &in.SignResponse, &out.SignResponse
		*out = new(bool)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SigningKp != nil {
		in, out := &in.SigningKp, &out.SigningKp
		*out = new(string)
		**out = **in
	}
	if in.SpBinding != nil {
		in, out := &in.SpBinding, &out.SpBinding
		*out = new(string)
		**out = **in
	}
	if in.URLSLOPost != nil {
		in, out := &in.URLSLOPost, &out.URLSLOPost
		*out = new(string)
		**out = **in
	}
	if in.URLSLORedirect != nil {
		in, out := &in.URLSLORedirect, &out.URLSLORedirect
		*out = new(string)
		**out = **in
	}
	if in.URLSsoInit != nil {
		in, out := &in.URLSsoInit, &out.URLSsoInit
		*out = new(string)
		**out = **in
	}
	if in.URLSsoPost != nil {
		in, out := &in.URLSsoPost, &out.URLSsoPost
		*out = new(string)
		**out = **in
	}
	if in.URLSsoRedirect != nil {
		in, out := &in.URLSsoRedirect, &out.URLSsoRedirect
		*out = new(string)
		**out = **in
	}
	if in.VerificationKp != nil {
		in, out := &in.VerificationKp, &out.VerificationKp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderInitParameters.
func (in *ProviderInitParameters) DeepCopy() *ProviderInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderList) DeepCopyInto(out *ProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Provider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderList.
func (in *ProviderList) DeepCopy() *ProviderList {
	if in == nil {
		return nil
	}
	out := new(ProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderObservation) DeepCopyInto(out *ProviderObservation) {
	*out = *in
	if in.AcsURL != nil {
		in, out := &in.AcsURL, &out.AcsURL
		*out = new(string)
		**out = **in
	}
	if in.AssertionValidNotBefore != nil {
		in, out := &in.AssertionValidNotBefore, &out.AssertionValidNotBefore
		*out = new(string)
		**out = **in
	}
	if in.AssertionValidNotOnOrAfter != nil {
		in, out := &in.AssertionValidNotOnOrAfter, &out.AssertionValidNotOnOrAfter
		*out = new(string)
		**out = **in
	}
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthnContextClassRefMapping != nil {
		in, out := &in.AuthnContextClassRefMapping, &out.AuthnContextClassRefMapping
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationFlow != nil {
		in, out := &in.AuthorizationFlow, &out.AuthorizationFlow
		*out = new(string)
		**out = **in
	}
	if in.DefaultRelayState != nil {
		in, out := &in.DefaultRelayState, &out.DefaultRelayState
		*out = new(string)
		**out = **in
	}
	if in.DigestAlgorithm != nil {
		in, out := &in.DigestAlgorithm, &out.DigestAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKp != nil {
		in, out := &in.EncryptionKp, &out.EncryptionKp
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InvalidationFlow != nil {
		in, out := &in.InvalidationFlow, &out.InvalidationFlow
		*out = new(string)
		**out = **in
	}
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDMapping != nil {
		in, out := &in.NameIDMapping, &out.NameIDMapping
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SessionValidNotOnOrAfter != nil {
		in, out := &in.SessionValidNotOnOrAfter, &out.SessionValidNotOnOrAfter
		*out = new(string)
		**out = **in
	}
	if in.SignAssertion != nil {
		in, out := &in.SignAssertion, &out.SignAssertion
		*out = new(bool)
		**out = **in
	}
	if in.SignResponse != nil {
		in, out := &in.SignResponse, &out.SignResponse
		*out = new(bool)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SigningKp != nil {
		in, out := &in.SigningKp, &out.SigningKp
		*out = new(string)
		**out = **in
	}
	if in.SpBinding != nil {
		in, out := &in.SpBinding, &out.SpBinding
		*out = new(string)
		**out = **in
	}
	if in.URLSLOPost != nil {
		in, out := &in.URLSLOPost, &out.URLSLOPost
		*out = new(string)
		**out = **in
	}
	if in.URLSLORedirect != nil {
		in, out := &in.URLSLORedirect, &out.URLSLORedirect
		*out = new(string)
		**out = **in
	}
	if in.URLSsoInit != nil {
		in, out := &in.URLSsoInit, &out.URLSsoInit
		*out = new(string)
		**out = **in
	}
	if in.URLSsoPost != nil {
		in, out := &in.URLSsoPost, &out.URLSsoPost
		*out = new(string)
		**out = **in
	}
	if in.URLSsoRedirect != nil {
		in, out := &in.URLSsoRedirect, &out.URLSsoRedirect
		*out = new(string)
		**out = **in
	}
	if in.VerificationKp != nil {
		in, out := &in.VerificationKp, &out.VerificationKp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderObservation.
func (in *ProviderObservation) DeepCopy() *ProviderObservation {
	if in == nil {
		return nil
	}
	out := new(ProviderObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderParameters) DeepCopyInto(out *ProviderParameters) {
	*out = *in
	if in.AcsURL != nil {
		in, out := &in.AcsURL, &out.AcsURL
		*out = new(string)
		**out = **in
	}
	if in.AssertionValidNotBefore != nil {
		in, out := &in.AssertionValidNotBefore, &out.AssertionValidNotBefore
		*out = new(string)
		**out = **in
	}
	if in.AssertionValidNotOnOrAfter != nil {
		in, out := &in.AssertionValidNotOnOrAfter, &out.AssertionValidNotOnOrAfter
		*out = new(string)
		**out = **in
	}
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthnContextClassRefMapping != nil {
		in, out := &in.AuthnContextClassRefMapping, &out.AuthnContextClassRefMapping
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationFlow != nil {
		in, out := &in.AuthorizationFlow, &out.AuthorizationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationFlowRef != nil {
		in, out := &in.AuthorizationFlowRef, &out.AuthorizationFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorizationFlowSelector != nil {
		in, out := &in.AuthorizationFlowSelector, &out.AuthorizationFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultRelayState != nil {
		in, out := &in.DefaultRelayState, &out.DefaultRelayState
		*out = new(string)
		**out = **in
	}
	if in.DigestAlgorithm != nil {
		in, out := &in.DigestAlgorithm, &out.DigestAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKp != nil {
		in, out := &in.EncryptionKp, &out.EncryptionKp
		*out = new(string)
		**out = **in
	}
	if in.InvalidationFlow != nil {
		in, out := &in.InvalidationFlow, &out.InvalidationFlow
		*out = new(string)
		**out = **in
	}
	if in.InvalidationFlowRef != nil {
		in, out := &in.InvalidationFlowRef, &out.InvalidationFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.InvalidationFlowSelector != nil {
		in, out := &in.InvalidationFlowSelector, &out.InvalidationFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDMapping != nil {
		in, out := &in.NameIDMapping, &out.NameIDMapping
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsRefs != nil {
		in, out := &in.PropertyMappingsRefs, &out.PropertyMappingsRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsSelector != nil {
		in, out := &in.PropertyMappingsSelector, &out.PropertyMappingsSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SessionValidNotOnOrAfter != nil {
		in, out := &in.SessionValidNotOnOrAfter, &out.SessionValidNotOnOrAfter
		*out = new(string)
		**out = **in
	}
	if in.SignAssertion != nil {
		in, out := &in.SignAssertion, &out.SignAssertion
		*out = new(bool)
		**out = **in
	}
	if in.SignResponse != nil {
		in, out := &in.SignResponse, &out.SignResponse
		*out = new(bool)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SigningKp != nil {
		in, out := &in.SigningKp, &out.SigningKp
		*out = new(string)
		**out = **in
	}
	if in.SpBinding != nil {
		in, out := &in.SpBinding, &out.SpBinding
		*out = new(string)
		**out = **in
	}
	if in.URLSLOPost != nil {
		in, out := &in.URLSLOPost, &out.URLSLOPost
		*out = new(string)
		**out = **in
	}
	if in.URLSLORedirect != nil {
		in, out := &in.URLSLORedirect, &out.URLSLORedirect
		*out = new(string)
		**out = **in
	}
	if in.URLSsoInit != nil {
		in, out := &in.URLSsoInit, &out.URLSsoInit
		*out = new(string)
		**out = **in
	}
	if in.URLSsoPost != nil {
		in, out := &in.URLSsoPost, &out.URLSsoPost
		*out = new(string)
		**out = **in
	}
	if in.URLSsoRedirect != nil {
		in, out := &in.URLSsoRedirect, &out.URLSsoRedirect
		*out = new(string)
		**out = **in
	}
	if in.VerificationKp != nil {
		in, out := &in.VerificationKp, &out.VerificationKp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderParameters.
func (in *ProviderParameters) DeepCopy() *ProviderParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPropertyMapping) DeepCopyInto(out *ProviderPropertyMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPropertyMapping.
func (in *ProviderPropertyMapping) DeepCopy() *ProviderPropertyMapping {
	if in == nil {
		return nil
	}
	out := new(ProviderPropertyMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderPropertyMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPropertyMappingInitParameters) DeepCopyInto(out *ProviderPropertyMappingInitParameters) {
	*out = *in
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.FriendlyName != nil {
		in, out := &in.FriendlyName, &out.FriendlyName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SAMLName != nil {
		in, out := &in.SAMLName, &out.SAMLName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPropertyMappingInitParameters.
func (in *ProviderPropertyMappingInitParameters) DeepCopy() *ProviderPropertyMappingInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderPropertyMappingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPropertyMappingList) DeepCopyInto(out *ProviderPropertyMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProviderPropertyMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPropertyMappingList.
func (in *ProviderPropertyMappingList) DeepCopy() *ProviderPropertyMappingList {
	if in == nil {
		return nil
	}
	out := new(ProviderPropertyMappingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderPropertyMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPropertyMappingObservation) DeepCopyInto(out *ProviderPropertyMappingObservation) {
	*out = *in
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.FriendlyName != nil {
		in, out := &in.FriendlyName, &out.FriendlyName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SAMLName != nil {
		in, out := &in.SAMLName, &out.SAMLName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPropertyMappingObservation.
func (in *ProviderPropertyMappingObservation) DeepCopy() *ProviderPropertyMappingObservation {
	if in == nil {
		return nil
	}
	out := new(ProviderPropertyMappingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPropertyMappingParameters) DeepCopyInto(out *ProviderPropertyMappingParameters) {
	*out = *in
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.FriendlyName != nil {
		in, out := &in.FriendlyName, &out.FriendlyName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SAMLName != nil {
		in, out := &in.SAMLName, &out.SAMLName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPropertyMappingParameters.
func (in *ProviderPropertyMappingParameters) DeepCopy() *ProviderPropertyMappingParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderPropertyMappingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPropertyMappingSpec) DeepCopyInto(out *ProviderPropertyMappingSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPropertyMappingSpec.
func (in *ProviderPropertyMappingSpec) DeepCopy() *ProviderPropertyMappingSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderPropertyMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPropertyMappingStatus) DeepCopyInto(out *ProviderPropertyMappingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPropertyMappingStatus.
func (in *ProviderPropertyMappingStatus) DeepCopy() *ProviderPropertyMappingStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderPropertyMappingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSpec) DeepCopyInto(out *ProviderSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSpec.
func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderStatus) DeepCopyInto(out *ProviderStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderStatus.
func (in *ProviderStatus) DeepCopy() *ProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Source) DeepCopyInto(out *Source) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Source.
func (in *Source) DeepCopy() *Source {
	if in == nil {
		return nil
	}
	out := new(Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Source) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceInitParameters) DeepCopyInto(out *SourceInitParameters) {
	*out = *in
	if in.AllowIdpInitiated != nil {
		in, out := &in.AllowIdpInitiated, &out.AllowIdpInitiated
		*out = new(bool)
		**out = **in
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BindingType != nil {
		in, out := &in.BindingType, &out.BindingType
		*out = new(string)
		**out = **in
	}
	if in.DigestAlgorithm != nil {
		in, out := &in.DigestAlgorithm, &out.DigestAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EncryptionKp != nil {
		in, out := &in.EncryptionKp, &out.EncryptionKp
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlowRef != nil {
		in, out := &in.EnrollmentFlowRef, &out.EnrollmentFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.EnrollmentFlowSelector != nil {
		in, out := &in.EnrollmentFlowSelector, &out.EnrollmentFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDPolicy != nil {
		in, out := &in.NameIDPolicy, &out.NameIDPolicy
		*out = new(string)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.PreAuthenticationFlow != nil {
		in, out := &in.PreAuthenticationFlow, &out.PreAuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.PreAuthenticationFlowRef != nil {
		in, out := &in.PreAuthenticationFlowRef, &out.PreAuthenticationFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.PreAuthenticationFlowSelector != nil {
		in, out := &in.PreAuthenticationFlowSelector, &out.PreAuthenticationFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroupRefs != nil {
		in, out := &in.PropertyMappingsGroupRefs, &out.PropertyMappingsGroupRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsGroupSelector != nil {
		in, out := &in.PropertyMappingsGroupSelector, &out.PropertyMappingsGroupSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PropertyMappingsRefs != nil {
		in, out := &in.PropertyMappingsRefs, &out.PropertyMappingsRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsSelector != nil {
		in, out := &in.PropertyMappingsSelector, &out.PropertyMappingsSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SLOURL != nil {
		in, out := &in.SLOURL, &out.SLOURL
		*out = new(string)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SigningKp != nil {
		in, out := &in.SigningKp, &out.SigningKp
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.SsoURL != nil {
		in, out := &in.SsoURL, &out.SsoURL
		*out = new(string)
		**out = **in
	}
	if in.TemporaryUserDeleteAfter != nil {
		in, out := &in.TemporaryUserDeleteAfter, &out.TemporaryUserDeleteAfter
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
	if in.VerificationKp != nil {
		in, out := &in.VerificationKp, &out.VerificationKp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceInitParameters.
func (in *SourceInitParameters) DeepCopy() *SourceInitParameters {
	if in == nil {
		return nil
	}
	out := new(SourceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceList) DeepCopyInto(out *SourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Source, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceList.
func (in *SourceList) DeepCopy() *SourceList {
	if in == nil {
		return nil
	}
	out := new(SourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceObservation) DeepCopyInto(out *SourceObservation) {
	*out = *in
	if in.AllowIdpInitiated != nil {
		in, out := &in.AllowIdpInitiated, &out.AllowIdpInitiated
		*out = new(bool)
		**out = **in
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.BindingType != nil {
		in, out := &in.BindingType, &out.BindingType
		*out = new(string)
		**out = **in
	}
	if in.DigestAlgorithm != nil {
		in, out := &in.DigestAlgorithm, &out.DigestAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EncryptionKp != nil {
		in, out := &in.EncryptionKp, &out.EncryptionKp
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDPolicy != nil {
		in, out := &in.NameIDPolicy, &out.NameIDPolicy
		*out = new(string)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.PreAuthenticationFlow != nil {
		in, out := &in.PreAuthenticationFlow, &out.PreAuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SLOURL != nil {
		in, out := &in.SLOURL, &out.SLOURL
		*out = new(string)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SigningKp != nil {
		in, out := &in.SigningKp, &out.SigningKp
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.SsoURL != nil {
		in, out := &in.SsoURL, &out.SsoURL
		*out = new(string)
		**out = **in
	}
	if in.TemporaryUserDeleteAfter != nil {
		in, out := &in.TemporaryUserDeleteAfter, &out.TemporaryUserDeleteAfter
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
	if in.VerificationKp != nil {
		in, out := &in.VerificationKp, &out.VerificationKp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceObservation.
func (in *SourceObservation) DeepCopy() *SourceObservation {
	if in == nil {
		return nil
	}
	out := new(SourceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceParameters) DeepCopyInto(out *SourceParameters) {
	*out = *in
	if in.AllowIdpInitiated != nil {
		in, out := &in.AllowIdpInitiated, &out.AllowIdpInitiated
		*out = new(bool)
		**out = **in
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BindingType != nil {
		in, out := &in.BindingType, &out.BindingType
		*out = new(string)
		**out = **in
	}
	if in.DigestAlgorithm != nil {
		in, out := &in.DigestAlgorithm, &out.DigestAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EncryptionKp != nil {
		in, out := &in.EncryptionKp, &out.EncryptionKp
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlowRef != nil {
		in, out := &in.EnrollmentFlowRef, &out.EnrollmentFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.EnrollmentFlowSelector != nil {
		in, out := &in.EnrollmentFlowSelector, &out.EnrollmentFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDPolicy != nil {
		in, out := &in.NameIDPolicy, &out.NameIDPolicy
		*out = new(string)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.PreAuthenticationFlow != nil {
		in, out := &in.PreAuthenticationFlow, &out.PreAuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.PreAuthenticationFlowRef != nil {
		in, out := &in.PreAuthenticationFlowRef, &out.PreAuthenticationFlowRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.PreAuthenticationFlowSelector != nil {
		in, out := &in.PreAuthenticationFlowSelector, &out.PreAuthenticationFlowSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroupRefs != nil {
		in, out := &in.PropertyMappingsGroupRefs, &out.PropertyMappingsGroupRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsGroupSelector != nil {
		in, out := &in.PropertyMappingsGroupSelector, &out.PropertyMappingsGroupSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PropertyMappingsRefs != nil {
		in, out := &in.PropertyMappingsRefs, &out.PropertyMappingsRefs
		*out = make([]v1.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsSelector != nil {
		in, out := &in.PropertyMappingsSelector, &out.PropertyMappingsSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SLOURL != nil {
		in, out := &in.SLOURL, &out.SLOURL
		*out = new(string)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SigningKp != nil {
		in, out := &in.SigningKp, &out.SigningKp
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.SsoURL != nil {
		in, out := &in.SsoURL, &out.SsoURL
		*out = new(string)
		**out = **in
	}
	if in.TemporaryUserDeleteAfter != nil {
		in, out := &in.TemporaryUserDeleteAfter, &out.TemporaryUserDeleteAfter
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
	if in.VerificationKp != nil {
		in, out := &in.VerificationKp, &out.VerificationKp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceParameters.
func (in *SourceParameters) DeepCopy() *SourceParameters {
	if in == nil {
		return nil
	}
	out := new(SourceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePropertyMapping) DeepCopyInto(out *SourcePropertyMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePropertyMapping.
func (in *SourcePropertyMapping) DeepCopy() *SourcePropertyMapping {
	if in == nil {
		return nil
	}
	out := new(SourcePropertyMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourcePropertyMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePropertyMappingInitParameters) DeepCopyInto(out *SourcePropertyMappingInitParameters) {
	*out = *in
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePropertyMappingInitParameters.
func (in *SourcePropertyMappingInitParameters) DeepCopy() *SourcePropertyMappingInitParameters {
	if in == nil {
		return nil
	}
	out := new(SourcePropertyMappingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePropertyMappingList) DeepCopyInto(out *SourcePropertyMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SourcePropertyMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePropertyMappingList.
func (in *SourcePropertyMappingList) DeepCopy() *SourcePropertyMappingList {
	if in == nil {
		return nil
	}
	out := new(SourcePropertyMappingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourcePropertyMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePropertyMappingObservation) DeepCopyInto(out *SourcePropertyMappingObservation) {
	*out = *in
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePropertyMappingObservation.
func (in *SourcePropertyMappingObservation) DeepCopy() *SourcePropertyMappingObservation {
	if in == nil {
		return nil
	}
	out := new(SourcePropertyMappingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePropertyMappingParameters) DeepCopyInto(out *SourcePropertyMappingParameters) {
	*out = *in
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePropertyMappingParameters.
func (in *SourcePropertyMappingParameters) DeepCopy() *SourcePropertyMappingParameters {
	if in == nil {
		return nil
	}
	out := new(SourcePropertyMappingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePropertyMappingSpec) DeepCopyInto(out *SourcePropertyMappingSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePropertyMappingSpec.
func (in *SourcePropertyMappingSpec) DeepCopy() *SourcePropertyMappingSpec {
	if in == nil {
		return nil
	}
	out := new(SourcePropertyMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePropertyMappingStatus) DeepCopyInto(out *SourcePropertyMappingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePropertyMappingStatus.
func (in *SourcePropertyMappingStatus) DeepCopy() *SourcePropertyMappingStatus {
	if in == nil {
		return nil
	}
	out := new(SourcePropertyMappingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSpec) DeepCopyInto(out *SourceSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSpec.
func (in *SourceSpec) DeepCopy() *SourceSpec {
	if in == nil {
		return nil
	}
	out := new(SourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceStatus) DeepCopyInto(out *SourceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceStatus.
func (in *SourceStatus) DeepCopy() *SourceStatus {
	if in == nil {
		return nil
	}
	out := new(SourceStatus)
	in.DeepCopyInto(out)
	return out
}
